#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
"""This is a quick script to take a BeerXML file and use it to produce an
h-recipe-marked HTML version of the recipe. Primarily intended to avoid
duplicating data entry work on my own brewing blog: http://is.gd/XPBrewing.

This script is copyright 2017 by Patrick Mooney. It is licensed under the GNU
GPL, either version 3 or (at your option) any later version. See the file 
LICENSE.md for details.
"""


import argparse

import pybeerxml    # [sudo] pip install [-U] pybeerxml; or see https://github.com/hotzenklotz/pybeerxml


def convert_to_hrecipe(i_file, o_file):
    """Uses pybeerxml to read the import file, then coughs out an appropriate HTML
    file, marked up with h-recipe. The input (and therefore output) file may
    contain more than one recipe.
    """
    parser = pybeerxml.Parser()
    recipes = parser.parse(i_file)
    with open(o_file, mode='w') as output_file:
        output_file.write('<!doctype html>\n<html>\n<head>\n<title>Conversion results for %s</title>\n</head>\n<body>\n\n' % i_file)
        output_file.write('<h1>Conversion results for %s</h1>\n\n' % i_file)
        output_file.write("""<p>This file was generated by <code><a rel="muse" href="">Patrick Mooney's beerxml-to-hrecipe</a></code>.</p>""")
        for r in recipes:
            # First, some basic recipe parameters
            output_file.write('<h2>%s</h2>\n\n' % r.name)
            output_file.write('<dl>\n<dt>O.G.:</dt> <dd>%.3f</dd>\n' % r.og)
            output_file.write('<dt>F.G.:</dt> <dd>%.3f</dd>\n' % r.fg)
            output_file.write('<dt>IBU:</dt> <dd>%.2f</dd>\n' % r.ibu)
            output_file.write('<dt>ABV.:</dt> <dd>%.2f</dd></dl>\n' % r.abv)
            
            # Next, ingredients
            output_file.write('<h3>Ingredients</h3>\n\n<ul>')
            for f in r.fermentables:
                output_file.write('  <li class="p-ingredient">%.2f&nbsp;lb. %s</li>' % (2.20462 * f.amount, f.name))
            for h in r.hops:
                output_file.write('  <li class="p-ingredient">%.2f&nbsp;oz. %s (%s%% A.A.) at %.0f min.</li>' % (2.20462 * 16 * h.amount, h.name, h.alpha, h.time))
            for y in r.yeasts:
                output_file.write('  <li class="p-ingredient">%s %s</li>' % (y.laboratory, y.name))
            output_file.write('</ul>')
        output_file.write("\n</body>\n</html>")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(epilog=__doc__)
    parser.add_argument('-i', '--input',  help="specify the input file.", required=True)
    parser.add_argument('-o', '--output', help="specify the output file.", required=True)
    args = vars(parser.parse_args())
    convert_to_hrecipe(args['input'], args['output'])
